# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: myStack 
Resources:
EC2Instance:
 Type: 'AWS::EC2::Instance'
 Properties:
   SecurityGroups:
     - !Ref InstanceSecurityGroup
   KeyName: udacity
   ImageId: 'ami-03d5c68bab01f3496'
   InstanceType: t2.micro
InstanceSecurityGroup:
 Type: 'AWS::EC2::SecurityGroup'
 Properties:
   GroupDescription: Enable SSH access via port 22
   SecurityGroupIngress:
     - IpProtocol: tcp
       FromPort: '22'
       ToPort: '22'
       CidrIp: 0.0.0.0/0