version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
        auth:
          username: $AWS_ACCESS_KEY_ID
          password: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation create --template-file template.yml --stack-name myStack --region us-west-2
      # Fail the job intentionally to simulate an error.
      # Uncomment the line below if you want to fail the current step
      # - run: return 1
      #- destroy_environment

workflows:
  my_workflow:
    jobs:
        - create_infrastructure